### ISSUE TITLE
AttributeError: 'MaxPool2DBackward' object has no attribute 'padding'

### ISSUE THREAD

**Issue by whuxujiyuan** [starimeL/PytorchConverter#5]
Got this error when converting model to ncnn, I'm using pytorch-0.3.0

**Comment by starimeL** [comment]
Not sure if there is any big change in the framework
Does it work well on your net in 2.0?

**Comment by tbenlyu** [comment]
I am converting https://download.pytorch.org/models/squeezenet1_1-f364aa15.pth, got the following problem:
ValueError: Unknown layer type: MaxPool2D, known types: dict_keys(['LeakyReLU', 'Add', 'data', 'Tanh', 'Addmm', 'Cmax', 'Dropout', 'Permute', 'MulConstant', 'AddConstant', 'Softmax', 'Index', 'View', 'ELU', 'ConvNd', 'MaxPool2d', 'BatchNorm', 'UpsamplingBilinear2d', 'PReLU', 'AvgPool2d', 'Negate', 'Threshold', 'Concat'])

I fixed MaxPool2d to MaxPool2D in the ConvertLayer_ncnn.py, and then got the same problem:
AttributeError: 'MaxPool2DBackward' object has no attribute 'padding'

**Comment by tbenlyu** [comment]
my pytorch:

pip3 install http://download.pytorch.org/whl/cpu/torch-0.3.0.post4-cp35-cp35m-linux_x86_64.whl 
pip3 install torchvision

**Comment by starimeL** [comment]
@tbenlyu 
Pytorch 0.3.0 changed some member variable name of the layer class, you can install the 0.2.0 to convert your net first.
I'll fix the name problem until 0.3.0 turns out to be a stable and major version:)

**Comment by tbenlyu** [comment]
Hi, I managed to convert the squeezenet 1.1 squeezenet1_1-f364aa15.pth from https://github.com/pytorch/vision/blob/master/torchvision/models/squeezenet.py
and I am testing it with https://github.com/Tencent/ncnn/blob/master/examples/squeezenet.cpp
I make some changes to squeezenet.cpp as below:
static int detect_squeezenet(const cv::Mat& bgr, std::vector<float>& cls_scores)
{
    ......

	ncnn::Mat in = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_BGR, bgr.cols, bgr.rows, 224, 224);

    ......

    ncnn::Mat out;
    ex.extract("View_1", out);
    cls_scores.resize(1000);
	
    const float* prob = out.channel(0);
    for (int j=0; j<1000; j++)
    {
        cls_scores[j] = prob[j];
    }

	......
}

Then I got the following different result:

corkscrew, bottle screw
syringe
airliner

the correct result should be (the same result from both pytorch squeezenet1_1-f364aa15.pth and your official (https://github.com/Tencent/ncnn/tree/master/examples) squeezenet_v1.1.param and squeezenet_v1.1.bin):

404 'airliner'
908 'wing'
405 'airship, dirigible'

I indicates that the converted ncnn model is not identical to the original pytorch model...

So I tries to compare my xxx.param with the official https://github.com/Tencent/ncnn/blob/master/examples/squeezenet_v1.1.param, I can see the parameters in the last 4 lines are a bit different:

Convolution      ConvNd_26        1 1 Dropout_1 ConvNd_26 0=1000 1=1 2=1 3=1 4=0 5=1 6=512000 //--->note: 4=1???
ReLU             Threshold_26     1 1 ConvNd_26 Threshold_26 0=0.000000
Pooling          AvgPool2d_1      1 1 Threshold_26 AvgPool2d_1 0=1 1=13 2=13 3=0 4=0 //--->note: 0=1 1=0 2=1 3=0 4=1????
Flatten          View_1           1 1 AvgPool2d_1 View_1  //--->note: this should be ok...

from https://github.com/Tencent/ncnn/blob/master/examples/squeezenet_v1.1.param:
Convolution      conv10           1 1 fire9/concat_drop9 conv10 0=1000 1=1 2=1 3=1 4=1 5=1 6=512000
ReLU             relu_conv10      1 1 conv10 conv10_relu_conv10 0=0.000000
Pooling          pool10           1 1 conv10_relu_conv10 pool10 0=1 1=0 2=1 3=0 4=1
Softmax          prob             1 1 pool10 prob 0=0

**Comment by tbenlyu** [comment]
btw, the shape(w,h,c) of out is (1000,1,1) in the converted model, which seems to be (1,1,1000) in your official model. whatever, let's say it is *data with 1000 float value. That's why I change squeezenet.cpp as above.

**Comment by starimeL** [comment]
@tbenlyu The torchvision pretrained squeezenet1_1-f364aa15.pth works fine on my local testing.
The most possible reasons causing such difference seems to be pixel normalization difference or BGR channel swapped. 
To make sure you feed exactly the same tensor input to pytorch and ncnn, you can refer to my updated test.py. And please also check the preprocessing in squeezenet.cpp

**Comment by tbenlyu** [comment]
great, thanks.
